repos:
  # misc
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-json
        files: .+\.json
      - id: pretty-format-json
        args:
          - "--autofix"
        files: .+\.json
      - id: check-yaml
        files: .*\.(yml|yaml)
      - id: sort-simple-yaml
        files: .*\.(yml|yaml)
#  # cloudformation/sam
#  - repo: https://github.com/awslabs/cfn-python-lint
#    rev: v0.65.0
#    hooks:
#      - id: cfn-python-lint
#        args:
#        - --config-file
#        - .cfnlintrc.yaml
